[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "ruff", only-features = [ "format", "diagnostics" ] },
  { name = "pyright", except-features = [ "format", "diagnostics" ] },
]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config]
documentFormatting = true 
settings.run = "onSave"

[language-server.pyright]
command = "pyright-langserver"
args = [ "--stdio" ]
config.reportMissingtypeStubs = false

# PKM tooling
[language-server.markdown-oxide]
command = "markdown-oxide"

[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]
auto-format = true
