# c-a prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# hot reload
bind r source-file ~/.config/tmux/tmux.conf

# mouse for ez
set -g mouse on
