# Generated by `rezoomie --show-completion` — do not edit by hand.
# Reinstall with: rezoomie --install-completion

function __rezoomie_root_args
    set -l tokens (commandline -opc)
    for i in (seq (count $tokens))
        if test "$tokens[$i]" = --root; and test (math $i + 1) -le (count $tokens)
            printf '%s\n' --root "$tokens[(math $i + 1)]"; return
        end
        if string match -qr '^--root=.+' -- $tokens[$i]
            printf '%s\n' $tokens[$i]; return
        end
    end
end

function __rezoomie_complete_render
    set -l tokens (commandline -opc)
    set -l n_pos 0
    set -l past_render 0
    for tok in $tokens
        if test $past_render -eq 1
            string match -qr '^-' -- $tok
            or set n_pos (math $n_pos + 1)
        end
        test "$tok" = render
        and set past_render 1
    end
    switch $n_pos
        case 0
            __fish_complete_path (commandline -t) "Resume TOML"
        case 1
            __fish_complete_path (commandline -t) "Template (.j2)"
    end
end

function __rezoomie_complete_role
    rezoomie (__rezoomie_root_args) role list --format tsv
end

function __rezoomie_complete_open_role
    rezoomie (__rezoomie_root_args) posting list --format tsv
end

# Disable file completion globally.
complete -c rezoomie -f

# Top-level subcommands.
complete -c rezoomie -n '__fish_use_subcommand' -a 'status' -d 'Show what is currently in staging/ and whether it is ready to commit or register.'
complete -c rezoomie -n '__fish_use_subcommand' -a 'db' -d 'Database management.'
complete -c rezoomie -n '__fish_use_subcommand' -a 'posting' -d 'Work with job postings.'
complete -c rezoomie -n '__fish_use_subcommand' -a 'resume' -d 'Work with resumes.'
complete -c rezoomie -n '__fish_use_subcommand' -a 'role' -d 'Work with roles.'

# Global options.
complete -c rezoomie -F -l root -d 'Project root directory. Defaults to cwd.'

# db subcommands.
complete -c rezoomie -n '__fish_seen_subcommand_from db; and not __fish_seen_subcommand_from migrate seed' -a 'migrate' -d 'Create the database if needed and apply any pending migrations.'
complete -c rezoomie -n '__fish_seen_subcommand_from db; and not __fish_seen_subcommand_from migrate seed' -a 'seed' -d 'Seed database tables from a parquet export directory.'

# db seed options.
complete -c rezoomie -n '__fish_seen_subcommand_from db; and __fish_seen_subcommand_from seed' -l dry-run -d 'Preview row counts without inserting (default).'
complete -c rezoomie -n '__fish_seen_subcommand_from db; and __fish_seen_subcommand_from seed' -l no-dry-run -d 'Preview row counts without inserting (default).'

# posting subcommands.
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and not __fish_seen_subcommand_from schema commit list show match bind' -a 'schema' -d 'Print the posting JSON Schema.'
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and not __fish_seen_subcommand_from schema commit list show match bind' -a 'commit' -d 'Write a posting TOML to postings/ with a date-slug filename.'
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and not __fish_seen_subcommand_from schema commit list show match bind' -a 'list' -d 'List committed postings. Use --format tsv for fzf piping.'
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and not __fish_seen_subcommand_from schema commit list show match bind' -a 'show' -d 'Emit a posting and its expectations/skills as TOML on stdout.'
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and not __fish_seen_subcommand_from schema commit list show match bind' -a 'match' -d 'Rank narratives by keyword overlap with a posting'\''s expectations and skills.

Default output is TSV (narrative_id, text), best match first:

  posting show <id> | posting match - | fzf --multi --with-nth=2.. | cut -f1

Use --format toml for [[jobs]]-grouped output suitable for agent workflows:

  posting show <id> | posting match - --format toml

See `posting schema` for TOML field reference.'
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and not __fish_seen_subcommand_from schema commit list show match bind' -a 'bind' -d 'Freeze a curation as a resume artifact, seeding any new bullets first.'

# posting list options.
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and __fish_seen_subcommand_from list' -l format -d 'Output format: '\''table'\'' (human-readable) or '\''tsv'\'' (fzf-ready).'

# posting match options.
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and __fish_seen_subcommand_from match' -l format -d 'Output format: '\''tsv'\'' (narrative_id, text) or '\''toml'\'' ([[jobs]] grouped by role).'

# resume subcommands.
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and not __fish_seen_subcommand_from list schema commit generate render' -a 'list' -d 'List committed resumes. Use --format tsv for fzf piping.'
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and not __fish_seen_subcommand_from list schema commit generate render' -a 'schema' -d 'Print the resume JSON Schema.'
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and not __fish_seen_subcommand_from list schema commit generate render' -a 'commit' -d 'Commit a resume draft: write all jobs/bullets/resume to DB and save to resumes/.'
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and not __fish_seen_subcommand_from list schema commit generate render' -a 'generate' -d 'Generate a tailored resume draft from a committed posting.'
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and not __fish_seen_subcommand_from list schema commit generate render' -a 'render' -d 'Render a resume TOML to .tex or .html using a Jinja2 template.'

# resume list options.
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and __fish_seen_subcommand_from list' -l format -a 'table tsv' -d 'Output format: '\''table'\'' (human-readable) or '\''tsv'\'' (fzf-ready).'

# resume render options.
complete -c rezoomie -F -n '__fish_seen_subcommand_from resume; and __fish_seen_subcommand_from render' -s o -l output -d 'Output file path. Defaults to stdout.'
complete -c rezoomie -F -n '__fish_seen_subcommand_from resume; and __fish_seen_subcommand_from render' -l css -d 'CSS file to inline into <style> tags (HTML only).'

# role subcommands.
complete -c rezoomie -n '__fish_seen_subcommand_from role; and not __fish_seen_subcommand_from commit find list show dump' -a 'commit' -d 'Seed the corpus: write roles, bullets, and attributions to the DB.'
complete -c rezoomie -n '__fish_seen_subcommand_from role; and not __fish_seen_subcommand_from commit find list show dump' -a 'find' -d 'Search roles by keyword and print (role_id, slug) pairs.'
complete -c rezoomie -n '__fish_seen_subcommand_from role; and not __fish_seen_subcommand_from commit find list show dump' -a 'list' -d 'List history roles. Use --format tsv for fzf piping.'
complete -c rezoomie -n '__fish_seen_subcommand_from role; and not __fish_seen_subcommand_from commit find list show dump' -a 'show' -d 'Emit a role and its bullets as a [[jobs]] TOML entry on stdout.'
complete -c rezoomie -n '__fish_seen_subcommand_from role; and not __fish_seen_subcommand_from commit find list show dump' -a 'dump' -d 'Emit all roles and bullets as TOML on stdout.'

# role list options.
complete -c rezoomie -n '__fish_seen_subcommand_from role; and __fish_seen_subcommand_from list' -l format -d 'Output format: '\''table'\'' (human-readable) or '\''tsv'\'' (fzf-ready).'

# Dynamic completions.
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and __fish_seen_subcommand_from bind' -a '(__rezoomie_complete_open_role)'
complete -c rezoomie -n '__fish_seen_subcommand_from posting; and __fish_seen_subcommand_from show' -a '(__rezoomie_complete_open_role)'
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and __fish_seen_subcommand_from generate' -a '(__rezoomie_complete_open_role)'
complete -c rezoomie -n '__fish_seen_subcommand_from resume; and __fish_seen_subcommand_from render' -a '(__rezoomie_complete_render)'
complete -c rezoomie -n '__fish_seen_subcommand_from role; and __fish_seen_subcommand_from show' -a '(__rezoomie_complete_role)'
